#!/bin/sh

alias ll="ls -lh"
alias la="ls -lAh"

# some colour plz
alias ls="ls --color=auto"
alias grep="grep --color"
alias diff="diff --color"

if [ "$DISTRO_FAMILY" = "debian" ] || [ "$DISTRO" = "debian" ]; then
    alias bat="batcat"
fi

