#!/bin/sh

export \
    EDITOR="nvim" \
    XDG_DATA_HOME="$HOME/.local/share" \
    XDG_CONFIG_HOME="$HOME/.config" \
    XDG_STATE_HOME="$HOME/.local/state" \
    XDG_CACHE_HOME="$HOME/.cache" \
	GOPATH="$XDG_DATA_HOME/go"
    PATH="$HOME/.local/bin:$GOPATH/bin:$PATH" \

# Better defaults to the less command
export LESSCHARSET="utf-8" \
   LESS="--tabs 4 --RAW-CONTROL-CHARS --quit-if-one-screen"

# Need to declare and export command evaluations separately otherwise export will
# mask the output and we won't know if the commands failed
DISTRO="$(grep "^ID=" /etc/os-release | cut -d = -f 2)"
DISTRO_FAMILY="$(grep "^ID_LIKE=" /etc/os-release | cut -d = -f 2)"
export DISTRO PATH
