#!/bin/sh

export \
    EDITOR="nvim" \
    XDG_DATA_HOME="$HOME/.local/share" \
    XDG_CONFIG_HOME="$HOME/.config" \
    XDG_STATE_HOME="$HOME/.local/state" \
    XDG_CACHE_HOME="$HOME/.cache"

export GOPATH="$XDG_DATA_HOME/go"

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# Better defaults to the less command
export LESSCHARSET="utf-8"

# Need to declare and export command evaluations separately otherwise export will
# mask the output and we won't know if the commands failed
DISTRO="$(grep "^ID=" /etc/os-release | cut -d = -f 2)"
DISTRO_FAMILY="$(grep "^ID_LIKE=" /etc/os-release | cut -d = -f 2)"
export DISTRO PATH

export PATH="$HOME/.local/bin:$PATH"
